In [1]:
import pandas as pd

matches = pd.read_csv("../Dataset/matches.csv")
deliveries = pd.read_csv("../Dataset/deliveries.csv")

print(matches.shape)
print(deliveries.shape)

matches.head()

(756, 18)
(179078, 21)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [2]:
print(matches.columns)

print("\n" + "="*50 + "\n")

print(deliveries.columns)

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

==================================================

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [3]:
total_matches = matches['id'].nunique()

total_teams = len(set(matches['team1']).union(set(matches['team2'])))

total_runs = deliveries['batsman_runs'].sum()

total_sixes = deliveries[deliveries['batsman_runs'] == 6].shape[0]

total_fours = deliveries[deliveries['batsman_runs'] == 4].shape[0]

print("Total Matches:", total_matches)
print("Total Teams:", total_teams)
print("Total Runs:", total_runs)
print("Total Sixes:", total_sixes)
print("Total Fours:", total_fours)

Total Matches: 756
Total Teams: 15
Total Runs: 223286
Total Sixes: 8170
Total Fours: 20392

In [4]:
team_wins = matches['winner'].value_counts()

print(team_wins.head(10))

winner
Mumbai Indians                 109
Chennai Super Kings            100
Kolkata Knight Riders           92
Royal Challengers Bangalore     84
Kings XI Punjab                 82
Rajasthan Royals                75
Delhi Daredevils                67
Sunrisers Hyderabad             58
Deccan Chargers                 29
Gujarat Lions                   13
Name: count, dtype: int64

In [5]:
top_batsmen = (
    deliveries.groupby('batsman')['batsman_runs']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

top_batsmen.head(10)

          batsman  batsman_runs
0         V Kohli          5434
1        SK Raina          5415
2       RG Sharma          4914
3       DA Warner          4741
4        S Dhawan          4632
5        CH Gayle          4560
6        MS Dhoni          4477
7      RV Uthappa          4446
8  AB de Villiers          4428
9       G Gambhir          4223

In [6]:
top_bowlers = (
    deliveries[deliveries['player_dismissed'].notna()]
    .groupby('bowler')['player_dismissed']
    .count()
    .sort_values(ascending=False)
    .reset_index()
)

top_bowlers.head(10)

            bowler  player_dismissed
0       SL Malinga               188
1         DJ Bravo               168
2         A Mishra               165
3  Harbhajan Singh               161
4        PP Chawla               156
5          B Kumar               141
6         R Ashwin               138
7        SP Narine               137
8         UT Yadav               136
9    R Vinay Kumar               127

In [7]:
most_sixes = (
    deliveries[deliveries['batsman_runs'] == 6]
    .groupby('batsman')
    .size()
    .sort_values(ascending=False)
    .reset_index(name='Sixes')
)

most_sixes.head(10)

          batsman  Sixes
0        CH Gayle    327
1  AB de Villiers    214
2        MS Dhoni    207
3        SK Raina    195
4       RG Sharma    194
5         V Kohli    191
6       DA Warner    181
7       SR Watson    177
8      KA Pollard    175
9       YK Pathan    161

In [8]:
most_fours = (
    deliveries[deliveries['batsman_runs'] == 4]
    .groupby('batsman')
    .size()
    .sort_values(ascending=False)
    .reset_index(name='Fours')
)

most_fours.head(10)

      batsman  Fours
0    S Dhawan    526
1    SK Raina    495
2   G Gambhir    492
3     V Kohli    482
4   DA Warner    459
5  RV Uthappa    436
6   RG Sharma    431
7   AM Rahane    405
8    CH Gayle    376
9    PA Patel    366

In [9]:
team_wins.reset_index().to_csv(
    '../dataset/team_wins.csv',
    index=False
)

top_batsmen.to_csv(
    '../dataset/top_batsmen.csv',
    index=False
)

top_bowlers.to_csv(
    '../dataset/top_bowlers.csv',
    index=False
)

most_sixes.to_csv(
    '../dataset/most_sixes.csv',
    index=False
)

most_fours.to_csv(
    '../dataset/most_fours.csv',
    index=False
)